name: 'command-tests'

on: [push]

jobs:
  command-job:
    runs-on: ubuntu-latest
    steps:
      - name: group-logging
        run: |
          echo '::group::group message'
          echo 'message 1'
          echo 'message 2'
          echo '::endgroup::'
      - name: 'step 1: create env variable'
        run: |
          echo "MYVAR=hi!" >> $GITHUB_ENV
      - name: 'step 2: use the env variable'
        run:
          echo $MYVAR