name: 'context-action'

on: [push]

jobs:
  context-job:
    runs-on: ubuntu-latest
    env:
      MY_ACTOR: ${{ github.actor }}
      MY_REPO: ${{ github.repository }}
    steps:
      - name: 'step 1'
        run: |
          echo "Hi $MY_ACTOR"
          echo "The repo is $MY_REPO"
